"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { Printer, ArrowLeft } from "lucide-react";
import type { AnalysisResult } from "@/lib/types";
import { loadAnalysis } from "@/lib/storage";
import { SeverityBadge, StatusBadge, CategoryBadge } from "@/components/Badges";

export default function ReportPage() {
  const params = useParams<{ id: string }>();
  const [analysis, setAnalysis] = useState<AnalysisResult | null | undefined>(undefined);

  useEffect(() => {
    if (params.id) loadAnalysis(params.id).then(setAnalysis);
  }, [params.id]);

  if (analysis === undefined) return null;
  if (analysis === null) {
    return (
      <main className="mx-auto max-w-content px-6 py-20 text-center">
        <p className="text-sm text-ink-muted">Report not found in this browser.</p>
        <Link href="/" className="mt-4 inline-block text-sm font-semibold text-violet-600">Start a new analysis</Link>
      </main>
    );
  }

  const sorted = [...analysis.issues].sort((a, b) => a.number - b.number);

  return (
    <main className="mx-auto max-w-content px-6 py-8 lg:px-10 print:px-0 print:py-0">
      <div className="flex flex-wrap items-center justify-between gap-3 print:hidden">
        <Link href={`/results/${analysis.id}`} className="inline-flex items-center gap-1.5 text-sm font-medium text-ink-soft hover:text-ink">
          <ArrowLeft size={15} /> Back to results
        </Link>
        <button
          onClick={() => window.print()}
          className="inline-flex items-center gap-1.5 rounded-lg bg-violet-600 px-3.5 py-2 text-sm font-semibold text-white hover:bg-violet-700"
        >
          <Printer size={15} /> Print / Save as PDF
        </button>
      </div>

      <div className="mt-6 rounded-2xl border border-border bg-white p-6 shadow-panel print:mt-0 print:rounded-none print:border-0 print:shadow-none">
        <h1 className="font-display text-2xl font-bold text-ink">Developer QA Report</h1>
        <p className="mt-1 text-sm text-ink-muted">Generated by DesignCheck on {new Date(analysis.createdAt).toLocaleString()}</p>

        <dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2">
          <div>
            <dt className="text-xs font-semibold uppercase tracking-wide text-ink-muted">Figma Design</dt>
            <dd className="truncate text-ink">{analysis.figmaUrl}</dd>
          </div>
          <div>
            <dt className="text-xs font-semibold uppercase tracking-wide text-ink-muted">Live Website</dt>
            <dd className="truncate text-ink">{analysis.websiteUrl}</dd>
          </div>
          <div>
            <dt className="text-xs font-semibold uppercase tracking-wide text-ink-muted">Viewport tested</dt>
            <dd className="text-ink">{analysis.viewport.label}</dd>
          </div>
          <div>
            <dt className="text-xs font-semibold uppercase tracking-wide text-ink-muted">Overall Match Score</dt>
            <dd className="text-ink">
              {analysis.overallScore}% (Visual {analysis.categoryScores.visual}% · Content {analysis.categoryScores.content}% ·
              Layout {analysis.categoryScores.layout}% · UX {analysis.categoryScores.ux}%)
            </dd>
          </div>
        </dl>
      </div>

      <div className="mt-6 space-y-4">
        {sorted.map((issue) => (
          <div
            key={issue.id}
            className="break-inside-avoid rounded-2xl border border-border bg-white p-5 shadow-panel print:rounded-none print:border print:shadow-none"
          >
            <div className="flex flex-wrap items-center justify-between gap-2">
              <h2 className="font-display text-base font-bold text-ink">
                Issue {issue.number} — {issue.title}
              </h2>
              <div className="flex gap-1.5">
                <SeverityBadge severity={issue.severity} />
                <CategoryBadge category={issue.category} />
                <StatusBadge status={issue.status} />
              </div>
            </div>

            <div className="mt-1 text-xs text-ink-muted">
              Page: {issue.page} · Section: {issue.section}
              {issue.matchConfidence !== null && <> · Match confidence: {issue.matchConfidence}%</>}
            </div>

            <div className="mt-4 grid gap-3 sm:grid-cols-2">
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-ink-muted">Expected (Figma)</p>
                <p className="mt-1 text-sm text-ink">{issue.expected}</p>
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-ink-muted">Actual (Website)</p>
                <p className="mt-1 text-sm text-ink">{issue.actual}</p>
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-ink-muted">Difference</p>
                <p className="mt-1 text-sm text-ink">{issue.difference}</p>
              </div>
              <div>
                <p className="text-xs font-semibold uppercase tracking-wide text-ink-muted">Website reference</p>
                <p className="mt-1 truncate text-sm text-ink">{issue.websiteSelector ?? "—"}</p>
              </div>
            </div>

            <div className="mt-3 rounded-lg bg-surface-sunken px-3 py-2.5">
              <p className="text-xs font-semibold uppercase tracking-wide text-ink-muted">Correction</p>
              <p className="mt-1 text-sm text-ink">{issue.correction}</p>
            </div>

            {issue.designerComment && (
              <div className="mt-3 rounded-lg border border-violet-100 bg-violet-50 px-3 py-2.5">
                <p className="text-xs font-semibold uppercase tracking-wide text-violet-700">Designer comment</p>
                <p className="mt-1 text-sm text-violet-900">{issue.designerComment}</p>
              </div>
            )}

            <div className="mt-3 print:hidden">
              <a
                href={analysis.isDemo ? `/demo-site?analysisId=${analysis.id}&issueId=${issue.id}` : analysis.website.url}
                target="_blank"
                rel="noreferrer"
                className="text-xs font-semibold text-violet-600 hover:text-violet-700"
              >
                Open on Website →
              </a>
            </div>
          </div>
        ))}
      </div>
    </main>
  );
}
